name: Performance Test
on: [push]
jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run k6 test
      uses: k6io/action@v0.1
      with:
        filename: TestENV/openAllReportsPage.js
    - name: Run k6 test
      uses: k6io/action@v0.1
      with:
        filename: TestENV/accessingAReport.js
